In [1]:
import numpy as np

In [19]:
import numpy as np


def create_coefficient_matrix(rows, cols, gamma, penalty):
    coefficient = np.zeros((rows * cols, rows * cols))
    free = np.zeros(rows * cols)

    for i in range(rows):
        for j in range(cols):
            index = i * cols + j  
            coefficient[index, index] = 1 

            neighbors = [(i-1, j), (i+1, j), (i, j-1), (i, j+1)] 
         
            if (i, j) == (0, 1):  # Клетка A
                next_index = 4 * cols + 1  # индекс A`
                coefficient[index, next_index] = (-1) * gamma
                free[index] = 10
            elif (i, j) == (0, 3):  # Клетка B
                next_index = 2 * cols + 3  # индекс B`
                coefficient[index, next_index] = (-1) * gamma
                free[index] = 5
            else:
                for neighbor_i, neighbor_j in neighbors:
                    if 0 <= neighbor_i < rows and 0 <= neighbor_j < cols:
                        neighbor_index = neighbor_i * cols + neighbor_j
                        coefficient[index, neighbor_index] -= gamma * 0.25 
                    else:
                        # Штраф за выход за пределы поля
                        coefficient[index, index] -= gamma * 0.25
                        free[index] += penalty * 0.25 

    return coefficient, free



In [22]:
def solve_equation(rows, cols, gamma, penalty):
    coefficient, free = create_coefficient_matrix(rows, cols, gamma, penalty)
    V = np.linalg.solve(coefficient, free)

    V_matrix = V.reshape((rows, cols))
    print("Функции ценности состояния:")
    print(V_matrix)




In [23]:
solve_equation(rows=5, cols=5, gamma=0.9, penalty=-1)

Функции ценности состояния:
[[ 3.30899634  8.78929186  4.42761918  5.32236759  1.49217876]
 [ 1.52158807  2.99231786  2.25013995  1.9075717   0.54740271]
 [ 0.05082249  0.73817059  0.67311326  0.35818621 -0.40314114]
 [-0.9735923  -0.43549543 -0.35488227 -0.58560509 -1.18307508]
 [-1.85770055 -1.34523126 -1.22926726 -1.42291815 -1.97517905]]
